on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: hydropho/go-jwt-auth:${{ GITHUB_SHA }}

  deploy:
    name: Deploy on K8S
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup helm
      uses: azure/setup-helm@v4
    - name: Configure kubeconfig
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}
    - name: Deploy the helm chart
      run: |
        helm install \
        --create-namespace \
        --namespace development \
        --set image=hydropho/go-jwt-auth:${{ GITHUB_SHA }} \
        --set dockerConfigJson.data="\{\"auths\":\{\"ghcr.io\":\{\"username\":\"${{ secrets.DOCKERHUB_USERNAME }}\"\,\"password\":\"${{ secrets.DOCKERHUB_TOKEN }}\"\}\}\}"

