on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build docker image
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push image
      uses: docker/build-and-push@v6
      with:
        context: .
        push: true
        tags: hydropho/go-jwt-auth:latest
